[theme]
primaryColor = "#1F77B4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E0E0E0"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false